name = "NumericalHeatTransfer"
uuid = "05ee7874-ddac-4dce-bacd-4833221f4dbe"
authors = ["Eric Wan <ewan2@illinois.edu> and contributors"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"